version: '3.8'

services:
  backend:
    build: ./app
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/mydatabase

  mongo:
    image: mongo
    volumes:
      - mongodb_data:/data/db

  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend

volumes:
  mongodb_data:
